% MetaAnalysisSingle.m
% -------------------------------------------------------------------------
% Purpose:
%   Visualizes transfer entropy (TE) results for a single animal by reading
%   output CSV files generated by TE scripts.
%
% Inputs:
%   - CSV file(s) produced by TransferEntropyKraskov, TransferEntropyKernel,
%     or ContinuousTransferEntropy
%
% Outputs:
%   - Figures summarizing TE directionality and magnitude for one animal
%
% File Relationships:
%   - Used after TE computation to visualize single-animal datasets
%   - Complements MetaAnalysisMulti and PlotVascularCorrelation
%
% Dependencies:
%   - MATLAB plotting functions
%
% ---- Original script content below ----

%Basic analysis on results (calculates average TE of a single animal)

days = [0, 1, 2, 3, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84];

shortenedResultsVSF1 = VSF1resultskraskov(ismember(VSF1resultskraskov.Day, days), :);

[i, dayNames] = findgroups(shortenedResultsVSF1.Day);
meanTEVSF1 = splitapply(@mean, shortenedResultsVSF1.TE_Rand_Dia, i);

stdTEVSF1 = splitapply(@std, shortenedResultsVSF1.TE_Rand_Dia, i);

figure;
errorbar(dayNames, meanTEVSF1, stdTEVSF1, '-o');
yLimits = [-0.1 0.1];
ylim(yLimits);
xlabel('Day');
ylabel('Mean TE across vessels');
title('TE for VSF1 after averaging all vessels together (rand)');
